### PR TITLE
2.4 - Upgrade CVE packages

### PR DESCRIPTION
**Pull request by subbarao-meduri**
Upgrade 
nats-server to 2.7.2, 
golang.org/x/crypto to v0.0.0-2021120292323-5770296d904e

Signed-off-by: Subbarao Meduri <smeduri@redhat.com>

### CODE REVIEW

**Comment by pshickeydev** [comment]
/hold

RC2 is currently being built for 2.4.4
Please wait to merge until the 2.4 branch is ready for new changes.

**Comment by pshickeydev** [comment]
/hold cancel

2.4.4 will need an RC3 so clear to merge

**Comment by pshickeydev** [comment]
@marcolan018 approve command appears to not have gone through. Could you resend that if you wouldn't mind?

**Review by marcolan018 — APPROVED** [review]
/approve

**Review by haoqing0110 — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
