### PR TITLE
[release-2.9] Change CGO_ENABLED to 1 / Changed TLS Version to 1.2

### PR DESCRIPTION
**Pull request by dislbenn**
**Changes:**  Changes the CGO_ENABLED flag to 1 / Changes TLS Version to 1.2.

### CODE REVIEW

**Comment by dislbenn** [comment]
/override main

Overriding these jobs to unblock PR. Jobs that are failing are due to the PR originally pointing to the `main`branch.

**Comment by clyang82** [comment]
@dislbenn Is it using in final grafana image?

**Comment by dislbenn** [comment]
@clyang82 yes, this will be using `CGO_ENALBED=1` in the final image.

**Comment by clyang82** [comment]
We are using https://github.com/stolostron/grafana/blob/release-2.9/Dockerfile.ocp for the final image.
It seems https://github.com/stolostron/grafana/tree/release-2.9/devenv#set-up-your-development-environment is for development only. is it necessary?

**Pull request merged**
